name = "dream-ai-lab"
compatibility_date = "2024-01-01"

[build]
command = "npm run build:static"
output_directory = "out"

[env.production]
name = "dream-ai-lab-production"

[env.staging]
name = "dream-ai-lab-staging" 